### ISSUE TITLE
returning and refresh token

### ISSUE THREAD

**Issue by mgenov** [mazine/oauth2-client-kotlin#1]
It would be nice if and refresh token is returned by the client as it may be used and by offline apps.

**Comment by mazine** [comment]
It actually is returned. Please check `OAuth2Client.codeRefreshToken()`.

**Comment by mgenov** [comment]
Yeah, but it returns only the refresh token. My suggestion was accessToken to be returned and with refreshToken in case such one is returned from the provider.
